esphome:
  name: roomba

esp8266:
  board: d1_mini

substitutions:
  name: "roomba"

# Enable logging
logger:
  hardware_uart: UART1

external_components:
  - source: components

sensor:
  - platform: roomba_component
    name: Roomba component

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200